### ISSUE TITLE
Unable to download all RNA Sequence Homo sapiens Data using the getData function

### ISSUE THREAD

**Issue by anishahaldar** [BgeeDB/BgeeDB_R#23]
I am trying to download all of the RNA sequence Homo sapiens Data from BgeeDB using this code.

`bgee_human <- BgeeDB::Bgee$new(species = "Homo_sapiens", speciesId = 9606, dataType = "rna_seq", pathToData = "/Volumes/Files")`

The Bgee object is created, but I then use the getData function using this code.

`bgee_data_human<-BgeeDB::getData(bgee_human)`.  

This is the error and output that I receive when I run this line of code. 

```
Saved annotation files in /Volumes/Files/Homo_sapiens_Bgee_14_2 folder.
downloading data from Bgee FTP...
You tried to download more than 15 experiments, because of that all the Bgee data for this species will be downloaded.
Downloading all expression data for species Homo_sapiens
Saved expression data file in/Volumes/Files/Homo_sapiens_Bgee_14_2folder. Now untar file...
Finished uncompress tar files
Save data in local sqlite database
cannot open file '/Volumes/Files/Homo_sapiens_Bgee_14_2/Homo_sapiens_RNA-Seq_read_counts_TPM_FPKM_E-MTAB-2449.tsv': No such file or directoryError in file(file, "rt") : cannot open the connection
```

I can successfully download individual RNA sequence experiments such as ERP000787, but I am running into issues when I download the entire RNA sequence data (15+ experiments).

**Comment by jwollbrett** [comment]
Hi @anishahaldar,

Thanks for the feedback.
Could you please provide more information about which version of BgeeDB do you use? Did you download it from Bioconductor or Github? If Bioconductor which release?
What is your OS? Linux, Mac, Windows?

**Comment by anishahaldar** [comment]
The version of BgeeDB that I am currently using is Version 2.16.0.  I downloaded it from Bioconductor.  The release for the Bioconductor is version 3.12, and I use macOS Version 12.1.

**Comment by jwollbrett** [comment]
Hello @anishahaldar,

Sorry for the late answer.
I tried to reproduce your error and found a bug when trying to donwload all human data from Bgee 14.2 with this release of the BgeeDB R package.
Unfortunately I am not able to push the hotfix to the release 3.12 of bioconductor. bioconductor does not allow to push to a branch corresponding to an old release....
If you want to access to all human processed expression values of Bgee 14.2, the best way to do it is to use the last release (BgeeDB 2.20.1 or after) of our package. The bug is not present in this version.
To download the last release of BgeeDB through Bioconductor (recommanded) you need to have R 4.1.0 installed.
The other option, if you don't want to update R, is to download the package through our github repo using devtools with the command `install_github("BgeeDB/BgeeDB_R`
For your information, you tried to download and load all human data in memory. For Bgee 14.2 those data are 64G big. Be sure you have enough RAM to load them. Otherwise, it is possible to focus on a subset of these data. The `getData()` function allows to  filter on experiment ID, library ID, anatomical entity ID, developmental stage ID, sex or strain.
