### ISSUE TITLE
Dog (Canis lupus familiaris) ensembl gene assembly update

### ISSUE THREAD

**Issue by HenrikCordes** [BgeeDB/BgeeDB_R#24]
Dear BgeeDB developers,

Just wanted to let you know that after the May 2021 update,  ensembl Dog genes are now annotated for Labrador retriever instead of Boxer, changing the naming space: 
e.g. for the ENPP1 gene, the post May 2021 ensembl ID of "ENSCAFG00000000001" in the Boxer breed changed to "ENSCAFG00845000008" for Labrador retriever breed.

I use the need biomart R package for further gene annotation making it difficult now.
My work around was to use a previous version 
`useMart('ensembl', dataset = 'clfamiliaris_gene_ensembl', host = 'https://may2021.archive.ensembl.org')`

But maybe you will change the annotation as well in a future BgeeDB release.

Keep up the great work! 

Best,
Henrik

**Comment by jwollbrett** [comment]
Hello @HenrikCordes,

Thanks for the feedback. 
We are currently finalizing the release of Bgee 15.0 that should be available soon. Unfortunately, the reference genome we used for this coming release are from Ensembl 102 (dec. 2020).
Updating reference genomes of species already present in Bgee 15.0 is not planned for the next minor Bgee 15.1 release that should be available in the second semester of 2022.
However, we are currently discussing the possibility to update our pipeline in order to add new species without processing data of already inserted ones. Updating the reference genome of a species already present in Bgee could potentially be part of this update.

Best,

Julien

**Comment by HenrikCordes** [comment]
Hi @jwollbrett,

thank you for the swift reply and you efforts keeping the annoations up to date!
The work around with an older version seems currently sufficient, but I'll look forward to the 15.1 release than :-)

Best
Henrik
