### ISSUE TITLE
loadTopAnatData  error

### ISSUE THREAD

**Issue by shubihu** [BgeeDB/BgeeDB_R#25]
when I lunch the loadTopAnatData  function , it always break in the third query. Even if I lunch the example as the fig2 , I got the same error.
![image](https://user-images.githubusercontent.com/36021958/173840402-c7ffe97d-8fdf-4509-9e25-bac476262053.png)

Fig2
![image](https://user-images.githubusercontent.com/36021958/173840708-d73aab88-f4c3-4d75-a1ae-3647c44a508b.png)

**Comment by jwollbrett** [comment]
Hello @shubihu ,

Thank you for your bug report.
In R the default timeout limit is 60 seconds. In the function `loadTopAnatData` we locally updated the timeout to 1200 seconds. The error you have happened because you reached this timeout when downloading expression data necessary to run topAnat.
This step has to be run once per species. 

In order to get rid of this error, I updated the default timeout used in `loadTopAnatData` to 1800 seconds. I also added a new parameter to this function in order to define the timeout you want. The new implementation will be available for the version 2.22.1 of the package. Once you have the new version you will be able to update the timeout by running the command :

``myTopAnatData <- loadTopAnatData(myBgeeObject = bgee, timeout = 3600)``

The new version will be available in Bioconductor in less than 2 days (they rebuild the packages every 48 hours). If you don't want to wait, you can also install the last version of BgeeDB from the master branch of our github repository.

We are currently investigating a solution to accelerate the loading of data for topAnat.

Do not hesitate to contact us if you have any other questions or problems running our R packages.

**Comment by shubihu** [comment]
Great ！Thank you !
